name: encuentra_u
description: Prototipo Flutter de EncuentraU con Clean Architecture y datos simulados.
publish_to: "none"
version: 0.1.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.6.0
  http_parser: ^4.1.2
  image_picker: ^1.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
